/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package absenapp;

import javax.swing.ButtonGroup;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author ferdy
 */
public class Absensi extends javax.swing.JFrame {

    Cetak c =  new Cetak();
    
    
    
    /**
     * Creates new form Absensi
     */
    public Absensi() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jKelas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kembaliAb = new javax.swing.JButton();
        siswa1 = new javax.swing.JLabel();
        h1 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        s1 = new javax.swing.JRadioButton();
        i1 = new javax.swing.JRadioButton();
        a1 = new javax.swing.JRadioButton();
        a2 = new javax.swing.JRadioButton();
        i2 = new javax.swing.JRadioButton();
        s2 = new javax.swing.JRadioButton();
        h2 = new javax.swing.JRadioButton();
        s3 = new javax.swing.JRadioButton();
        i3 = new javax.swing.JRadioButton();
        a3 = new javax.swing.JRadioButton();
        h3 = new javax.swing.JRadioButton();
        a4 = new javax.swing.JRadioButton();
        i4 = new javax.swing.JRadioButton();
        s4 = new javax.swing.JRadioButton();
        h4 = new javax.swing.JRadioButton();
        s5 = new javax.swing.JRadioButton();
        i5 = new javax.swing.JRadioButton();
        a5 = new javax.swing.JRadioButton();
        h5 = new javax.swing.JRadioButton();
        a6 = new javax.swing.JRadioButton();
        i6 = new javax.swing.JRadioButton();
        s6 = new javax.swing.JRadioButton();
        h6 = new javax.swing.JRadioButton();
        s7 = new javax.swing.JRadioButton();
        i7 = new javax.swing.JRadioButton();
        a7 = new javax.swing.JRadioButton();
        h7 = new javax.swing.JRadioButton();
        a8 = new javax.swing.JRadioButton();
        i8 = new javax.swing.JRadioButton();
        s8 = new javax.swing.JRadioButton();
        h8 = new javax.swing.JRadioButton();
        s9 = new javax.swing.JRadioButton();
        i9 = new javax.swing.JRadioButton();
        a9 = new javax.swing.JRadioButton();
        h9 = new javax.swing.JRadioButton();
        siswa2 = new javax.swing.JLabel();
        siswa3 = new javax.swing.JLabel();
        siswa4 = new javax.swing.JLabel();
        siswa8 = new javax.swing.JLabel();
        siswa7 = new javax.swing.JLabel();
        siswa6 = new javax.swing.JLabel();
        siswa5 = new javax.swing.JLabel();
        siswa9 = new javax.swing.JLabel();
        nextCetak = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Depan Belakang");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Depan Belakang");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELAMAT DATANG");

        jPanel2.setBackground(new java.awt.Color(52, 152, 219));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SELAMAT DATANG");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Depan Belakang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        jKelas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jKelas.setForeground(new java.awt.Color(255, 255, 255));
        jKelas.setText("6");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kelas");

        kembaliAb.setBackground(new java.awt.Color(255, 255, 255));
        kembaliAb.setText("Kembali");
        kembaliAb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliAbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jKelas)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(kembaliAb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(53, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(45, 45, 45)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(kembaliAb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jKelas)
                .addGap(206, 206, 206))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(236, 236, 236)
                    .addComponent(jLabel8)
                    .addContainerGap(235, Short.MAX_VALUE)))
        );

        siswa1.setBackground(new java.awt.Color(51, 51, 51));
        siswa1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        siswa1.setForeground(new java.awt.Color(51, 51, 51));
        siswa1.setText("Ahmad Abdul");

        buttonGroup1.add(h1);
        h1.setActionCommand("Hadir");
        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Hadir");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Sakit");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Izin");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Alpha");

        buttonGroup1.add(s1);
        s1.setActionCommand("Sakit");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(i1);
        i1.setActionCommand("Izin");
        i1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(a1);
        a1.setActionCommand("Alpha");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(a2);
        a2.setActionCommand("Alpha");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(i2);
        i2.setActionCommand("Izin");
        i2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(s2);
        s2.setActionCommand("Sakit");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(h2);
        h2.setActionCommand("Hadir");
        h2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(s3);
        s3.setActionCommand("Sakit");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        buttonGroup3.add(i3);
        i3.setActionCommand("Izin");
        i3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i3ActionPerformed(evt);
            }
        });

        buttonGroup3.add(a3);
        a3.setActionCommand("Alpha");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });

        buttonGroup3.add(h3);
        h3.setActionCommand("Hadir");
        h3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h3ActionPerformed(evt);
            }
        });

        buttonGroup4.add(a4);
        a4.setActionCommand("Alpha");
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });

        buttonGroup4.add(i4);
        i4.setActionCommand("Izin");
        i4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i4ActionPerformed(evt);
            }
        });

        buttonGroup4.add(s4);
        s4.setActionCommand("Sakit");
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });

        buttonGroup4.add(h4);
        h4.setActionCommand("Hadir");
        h4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h4ActionPerformed(evt);
            }
        });

        buttonGroup5.add(s5);
        s5.setActionCommand("Sakit");
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });

        buttonGroup5.add(i5);
        i5.setActionCommand("Izin");
        i5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i5ActionPerformed(evt);
            }
        });

        buttonGroup5.add(a5);
        a5.setActionCommand("Alpha");
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });

        buttonGroup5.add(h5);
        h5.setActionCommand("Hadir");
        h5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h5ActionPerformed(evt);
            }
        });

        buttonGroup6.add(a6);
        a6.setActionCommand("Alpha");
        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });

        buttonGroup6.add(i6);
        i6.setActionCommand("Izin");
        i6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i6ActionPerformed(evt);
            }
        });

        buttonGroup6.add(s6);
        s6.setActionCommand("Sakit");
        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });

        buttonGroup6.add(h6);
        h6.setActionCommand("Hadir");
        h6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h6ActionPerformed(evt);
            }
        });

        buttonGroup7.add(s7);
        s7.setActionCommand("Sakit");
        s7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s7ActionPerformed(evt);
            }
        });

        buttonGroup7.add(i7);
        i7.setActionCommand("Izin");
        i7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i7ActionPerformed(evt);
            }
        });

        buttonGroup7.add(a7);
        a7.setActionCommand("Alpha");
        a7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a7ActionPerformed(evt);
            }
        });

        buttonGroup7.add(h7);
        h7.setActionCommand("Hadir");
        h7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h7ActionPerformed(evt);
            }
        });

        buttonGroup8.add(a8);
        a8.setActionCommand("Alpha");
        a8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a8ActionPerformed(evt);
            }
        });

        buttonGroup8.add(i8);
        i8.setActionCommand("Izin");
        i8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i8ActionPerformed(evt);
            }
        });

        buttonGroup8.add(s8);
        s8.setActionCommand("Sakit");
        s8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s8ActionPerformed(evt);
            }
        });

        buttonGroup8.add(h8);
        h8.setActionCommand("Hadir");
        h8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h8ActionPerformed(evt);
            }
        });

        buttonGroup9.add(s9);
        s9.setActionCommand("Sakit");
        s9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s9ActionPerformed(evt);
            }
        });

        buttonGroup9.add(i9);
        i9.setActionCommand("Izin");
        i9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i9ActionPerformed(evt);
            }
        });

        buttonGroup9.add(a9);
        a9.setActionCommand("Alpha");
        a9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a9ActionPerformed(evt);
            }
        });

        buttonGroup9.add(h9);
        h9.setActionCommand("Hadir");
        h9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h9ActionPerformed(evt);
            }
        });

        siswa2.setBackground(new java.awt.Color(51, 51, 51));
        siswa2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        siswa2.setForeground(new java.awt.Color(51, 51, 51));
        siswa2.setText("Ananada Bachdim");

        siswa3.setBackground(new java.awt.Color(51, 51, 51));
        siswa3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        siswa3.setForeground(new java.awt.Color(51, 51, 51));
        siswa3.setText("Bella Anisa");

        siswa4.setBackground(new java.awt.Color(51, 51, 51));
        siswa4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        siswa4.setForeground(new java.awt.Color(51, 51, 51));
        siswa4.setText("Danang Prayoga");

        siswa8.setBackground(new java.awt.Color(51, 51, 51));
        siswa8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        siswa8.setForeground(new java.awt.Color(51, 51, 51));
        siswa8.setText("Syarif Putra Pratama");

        siswa7.setBackground(new java.awt.Color(51, 51, 51));
        siswa7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        siswa7.setForeground(new java.awt.Color(51, 51, 51));
        siswa7.setText("Muhammad Fajar");

        siswa6.setBackground(new java.awt.Color(51, 51, 51));
        siswa6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        siswa6.setForeground(new java.awt.Color(51, 51, 51));
        siswa6.setText("Nina Septiani");

        siswa5.setBackground(new java.awt.Color(51, 51, 51));
        siswa5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        siswa5.setForeground(new java.awt.Color(51, 51, 51));
        siswa5.setText("Galih Kusuma");

        siswa9.setBackground(new java.awt.Color(51, 51, 51));
        siswa9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        siswa9.setForeground(new java.awt.Color(51, 51, 51));
        siswa9.setText("Yuliani Putri");

        nextCetak.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nextCetak.setText("SELANJUTNYA");
        nextCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel10)
                                .addGap(149, 149, 149))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(siswa1)
                                        .addGap(183, 183, 183)
                                        .addComponent(h1)
                                        .addGap(82, 82, 82)
                                        .addComponent(s1)
                                        .addGap(72, 72, 72)
                                        .addComponent(i1))
                                    .addComponent(siswa4)
                                    .addComponent(siswa3)
                                    .addComponent(siswa2)
                                    .addComponent(siswa5)
                                    .addComponent(siswa8)
                                    .addComponent(siswa7)
                                    .addComponent(siswa6)
                                    .addComponent(siswa9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a2)
                            .addComponent(a1)
                            .addComponent(a4)
                            .addComponent(a3)
                            .addComponent(a6)
                            .addComponent(a5)
                            .addComponent(a8)
                            .addComponent(a7))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(h8)
                                        .addGap(82, 82, 82)
                                        .addComponent(s8)
                                        .addGap(72, 72, 72)
                                        .addComponent(i8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(h6)
                                        .addGap(82, 82, 82)
                                        .addComponent(s6)
                                        .addGap(72, 72, 72)
                                        .addComponent(i6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(h7)
                                        .addGap(82, 82, 82)
                                        .addComponent(s7)
                                        .addGap(72, 72, 72)
                                        .addComponent(i7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(h9)
                                        .addGap(82, 82, 82)
                                        .addComponent(s9)
                                        .addGap(72, 72, 72)
                                        .addComponent(i9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(a9)))
                                .addGap(66, 66, 66))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(h4)
                                        .addGap(82, 82, 82)
                                        .addComponent(s4)
                                        .addGap(72, 72, 72)
                                        .addComponent(i4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(h2)
                                        .addGap(82, 82, 82)
                                        .addComponent(s2)
                                        .addGap(72, 72, 72)
                                        .addComponent(i2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(h3)
                                        .addGap(82, 82, 82)
                                        .addComponent(s3)
                                        .addGap(72, 72, 72)
                                        .addComponent(i3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(h5)
                                        .addGap(82, 82, 82)
                                        .addComponent(s5)
                                        .addGap(72, 72, 72)
                                        .addComponent(i5)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nextCetak)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel12)))
                        .addGap(47, 47, 47))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {a1, h1, i1, s1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(siswa9)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(siswa1)
                            .addComponent(h1)
                            .addComponent(s1)
                            .addComponent(i1)
                            .addComponent(a1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(h2)
                            .addComponent(s2)
                            .addComponent(i2)
                            .addComponent(a2)
                            .addComponent(siswa2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h3)
                                    .addComponent(s3)
                                    .addComponent(i3)
                                    .addComponent(a3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h4)
                                    .addComponent(s4)
                                    .addComponent(i4)
                                    .addComponent(a4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(siswa3)
                                .addGap(18, 18, 18)
                                .addComponent(siswa4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h5)
                                    .addComponent(s5)
                                    .addComponent(i5)
                                    .addComponent(a5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h6)
                                    .addComponent(s6)
                                    .addComponent(i6)
                                    .addComponent(a6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h7)
                                    .addComponent(s7)
                                    .addComponent(i7)
                                    .addComponent(a7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h8)
                                    .addComponent(s8)
                                    .addComponent(i8)
                                    .addComponent(a8)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(siswa5)
                                .addGap(18, 18, 18)
                                .addComponent(siswa6)
                                .addGap(18, 18, 18)
                                .addComponent(siswa7)
                                .addGap(18, 18, 18)
                                .addComponent(siswa8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(h9)
                            .addComponent(s9)
                            .addComponent(i9)
                            .addComponent(a9))))
                .addGap(18, 18, 18)
                .addComponent(nextCetak, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        h1.setSelected(false);
    }//GEN-LAST:event_h1ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        
    }//GEN-LAST:event_s1ActionPerformed

    private void i1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i1ActionPerformed
        
        
    }//GEN-LAST:event_i1ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        
    }//GEN-LAST:event_a1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        
    }//GEN-LAST:event_a2ActionPerformed

    private void i2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i2ActionPerformed
        
    }//GEN-LAST:event_i2ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        
    }//GEN-LAST:event_s2ActionPerformed

    private void h2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2ActionPerformed
        
    }//GEN-LAST:event_h2ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        
    }//GEN-LAST:event_s3ActionPerformed

    private void i3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i3ActionPerformed
        
    }//GEN-LAST:event_i3ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        
    }//GEN-LAST:event_a3ActionPerformed

    private void h3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h3ActionPerformed
     
       
    }//GEN-LAST:event_h3ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
       
    }//GEN-LAST:event_a4ActionPerformed

    private void i4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i4ActionPerformed
       
    }//GEN-LAST:event_i4ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
       
    }//GEN-LAST:event_s4ActionPerformed

    private void h4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h4ActionPerformed
        
    }//GEN-LAST:event_h4ActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        
    }//GEN-LAST:event_s5ActionPerformed

    private void i5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i5ActionPerformed
       
    }//GEN-LAST:event_i5ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
        
    }//GEN-LAST:event_a5ActionPerformed

    private void h5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h5ActionPerformed
        
    }//GEN-LAST:event_h5ActionPerformed

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        
    }//GEN-LAST:event_a6ActionPerformed

    private void i6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i6ActionPerformed
       
    }//GEN-LAST:event_i6ActionPerformed

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed
       
    }//GEN-LAST:event_s6ActionPerformed

    private void h6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h6ActionPerformed
        
    }//GEN-LAST:event_h6ActionPerformed

    private void s7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s7ActionPerformed
       
    }//GEN-LAST:event_s7ActionPerformed

    private void i7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i7ActionPerformed
        
    }//GEN-LAST:event_i7ActionPerformed

    private void a7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a7ActionPerformed
        
    }//GEN-LAST:event_a7ActionPerformed

    private void h7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h7ActionPerformed
        
    }//GEN-LAST:event_h7ActionPerformed

    private void a8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a8ActionPerformed
        
    }//GEN-LAST:event_a8ActionPerformed

    private void i8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i8ActionPerformed
        
    }//GEN-LAST:event_i8ActionPerformed

    private void s8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s8ActionPerformed
        
    }//GEN-LAST:event_s8ActionPerformed

    private void h8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h8ActionPerformed
        
    }//GEN-LAST:event_h8ActionPerformed

    private void s9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s9ActionPerformed
        
    }//GEN-LAST:event_s9ActionPerformed

    private void i9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i9ActionPerformed
        
    }//GEN-LAST:event_i9ActionPerformed

    private void a9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a9ActionPerformed
       
    }//GEN-LAST:event_a9ActionPerformed

    private void h9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h9ActionPerformed
      
    }//GEN-LAST:event_h9ActionPerformed

    private void nextCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextCetakActionPerformed
        
        
        try{
                Cetak cet = new Cetak();
                
                cet.pack();
                cet.setLocationRelativeTo(null);
                
                Calendar timer = Calendar.getInstance();
                timer.getTime();
                SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
                tTime.format(timer.getTime());
                SimpleDateFormat tDate = new SimpleDateFormat("dd-MMM-yyyy");
                tDate.format(timer.getTime());
                
                Cetak.jTextArea_lembar.append  (
                "\t\t Data Absensi Kelas "
                + Absensi.jKelas.getText() + "\n\n" +
                "Tanggal : " + tDate.format(timer.getTime()) + "\n\n" +
                siswa1.getText()+ "\t\t\t" + buttonGroup1.getSelection().getActionCommand() + "\n\n" +
                siswa2.getText()+ "\t\t\t" + buttonGroup2.getSelection().getActionCommand() + "\n\n" +
                siswa3.getText()+ "\t\t\t" + buttonGroup3.getSelection().getActionCommand() + "\n\n" +
                siswa4.getText()+ "\t\t\t" + buttonGroup4.getSelection().getActionCommand() + "\n\n" +
                siswa5.getText()+ "\t\t\t" + buttonGroup5.getSelection().getActionCommand() + "\n\n" +
                siswa6.getText()+ "\t\t\t" + buttonGroup6.getSelection().getActionCommand() + "\n\n" +
                siswa7.getText()+ "\t\t\t" + buttonGroup7.getSelection().getActionCommand() + "\n\n" +
                siswa8.getText()+ "\t\t" + buttonGroup8.getSelection().getActionCommand() + "\n\n" + 
                siswa9.getText()+ "\t\t\t" + buttonGroup9.getSelection().getActionCommand() + "\n\n\n\n"
                );
                Cetak.kelas_cet.setText(jKelas.getText()); 
                cet.setVisible(true);
                this.dispose();
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this,"Masih ada murid belum terabsen!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_nextCetakActionPerformed

    private void kembaliAbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliAbActionPerformed
        Home hm = new Home();
        hm.pack();
        hm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_kembaliAbActionPerformed
    
    private JFrame frame;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Absensi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a3;
    private javax.swing.JRadioButton a4;
    private javax.swing.JRadioButton a5;
    private javax.swing.JRadioButton a6;
    private javax.swing.JRadioButton a7;
    private javax.swing.JRadioButton a8;
    private javax.swing.JRadioButton a9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JRadioButton h1;
    private javax.swing.JRadioButton h2;
    private javax.swing.JRadioButton h3;
    private javax.swing.JRadioButton h4;
    private javax.swing.JRadioButton h5;
    private javax.swing.JRadioButton h6;
    private javax.swing.JRadioButton h7;
    private javax.swing.JRadioButton h8;
    private javax.swing.JRadioButton h9;
    private javax.swing.JRadioButton i1;
    private javax.swing.JRadioButton i2;
    private javax.swing.JRadioButton i3;
    private javax.swing.JRadioButton i4;
    private javax.swing.JRadioButton i5;
    private javax.swing.JRadioButton i6;
    private javax.swing.JRadioButton i7;
    private javax.swing.JRadioButton i8;
    private javax.swing.JRadioButton i9;
    public static javax.swing.JLabel jKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JButton kembaliAb;
    private javax.swing.JButton nextCetak;
    private javax.swing.JRadioButton s1;
    private javax.swing.JRadioButton s2;
    private javax.swing.JRadioButton s3;
    private javax.swing.JRadioButton s4;
    private javax.swing.JRadioButton s5;
    private javax.swing.JRadioButton s6;
    private javax.swing.JRadioButton s7;
    private javax.swing.JRadioButton s8;
    private javax.swing.JRadioButton s9;
    public static javax.swing.JLabel siswa1;
    public static javax.swing.JLabel siswa2;
    public static javax.swing.JLabel siswa3;
    public static javax.swing.JLabel siswa4;
    public static javax.swing.JLabel siswa5;
    public static javax.swing.JLabel siswa6;
    public static javax.swing.JLabel siswa7;
    public static javax.swing.JLabel siswa8;
    public static javax.swing.JLabel siswa9;
    // End of variables declaration//GEN-END:variables

    private void k(String a) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
